apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: rag-bot
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: karimbk/frontend-llm:latest
        ports:
        - containerPort: 8501
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: rag-bot
  labels:
    app: streamlit-app
spec:
  selector:
    app: streamlit-app
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
