apiVersion: v1
kind: PersistentVolume
metadata:
  name: chroma-pv
  namespace: rag-bot
  labels:
    app: chroma
spec:
  storageClassName: slow
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/chroma # Local path on the Kubernetes node (use only for local development)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  namespace: rag-bot
  labels:
    app: chroma
spec: 
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
